name: Windows build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Build and run main
      run: go run main.go --add-headers --lic-server https://drm-widevine-licensing.axtest.net/AcquireLicense --pssh AAAAXHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADwSEDAvgN1BHkiGvKW7H4AYoCQSEDAvgN1BHkiGvKW7H4AYoCQSEDAvgN1BHkiGvKW7H4AYoCRI88aJmwY=

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-artifact
        path: ${{github.workspace}}/test.exe
        if-no-files-found: ignore
        retention-days: 0
