name: Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Run main
      run: go run main.go
